import { Project } from "@/hooks/use-project-store";

export const initialProjects: Project[] = [
  {
    id: "proj_villa_1",
    title: "بناء فيلا فاخرة في حي الياسمين",
    status: "قيد التنفيذ",
    variant: "default",
    location: "الرياض، حي الياسمين",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "luxury villa modern",
    progress: 65,
    budget: 3500000,
    currency: "SAR",
    lat: 24.8136,
    lng: 46.6753,
    manager: "علي محمد",
    endDate: "2025-12-31",
    createdAt: "2024-01-15T10:00:00Z",
    projectType: 'residential_villa',
    quality: 'luxury',
    scopeOfWork: 'بناء فيلا سكنية فاخرة بمساحة 600 متر مربع في حي الياسمين بالرياض، تتكون من دورين وملحق علوي. يشمل العمل جميع مراحل الإنشاء من الحفر والأساسات والخرسانات والمباني، بالإضافة إلى أعمال التشطيبات الداخلية والخارجية بمستوى فاخر، وتنسيق الحدائق والمسبح الخارجي.'
  },
  {
    id: "proj_mall_2",
    title: "تطوير مول الرياض بارك",
    status: "مخطط له",
    variant: "outline",
    location: "الرياض، الطريق الدائري الشمالي",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "shopping mall interior",
    progress: 10,
    budget: 150000000,
    currency: "SAR",
    lat: 24.7615,
    lng: 46.6412,
    manager: "فاطمة الزهراني",
    endDate: "2026-10-01",
    createdAt: "2024-05-20T11:30:00Z",
    projectType: 'retail_mall',
    quality: 'premium',
    scopeOfWork: 'مشروع تطوير وتوسعة مول الرياض بارك، يشمل إضافة منطقة تجارية جديدة بمساحة 20,000 متر مربع، وتطوير الواجهات الخارجية، وإعادة تصميم منطقة المطاعم والترفيه.'
  },
  {
    id: "proj_tower_3",
    title: "إنشاء برج المكاتب الذكي بجدة",
    status: "قيد التنفيذ",
    variant: "default",
    location: "جدة، طريق الملك عبدالعزيز",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "office tower skyscraper",
    progress: 40,
    budget: 250000000,
    currency: "SAR",
    lat: 21.5433,
    lng: 39.1728,
    manager: "خالد الغامدي",
    endDate: "2027-06-30",
    createdAt: "2023-11-01T09:00:00Z",
    projectType: 'office_high_rise',
    quality: 'luxury',
    scopeOfWork: 'بناء برج مكتبي بارتفاع 30 طابقًا على طريق الملك عبدالعزيز في جدة، مع واجهات زجاجية حديثة وأنظمة ذكية لإدارة المباني ومواقف سيارات متعددة الطوابق.'
  },
  {
    id: "proj_event_4",
    title: "تجهيز فعالية إطلاق سيارة كهربائية",
    status: "مكتمل",
    variant: "secondary",
    location: "الدمام، مركز المعارض",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "event setup stage",
    progress: 100,
    budget: 850000,
    currency: "SAR",
    lat: 26.3927,
    lng: 49.9774,
    manager: "نورة القحطاني",
    endDate: "2024-06-15",
    createdAt: "2024-04-01T14:00:00Z",
    projectType: 'event_setup',
    quality: 'premium',
    scopeOfWork: 'تجهيز كامل لفعالية إطلاق سيارة كهربائية جديدة، يشمل بناء المسرح الرئيسي، وتوفير أنظمة الصوت والإضاءة والشاشات، وتصميم وتصنيع أجنحة العرض، وتنظيم منطقة استقبال كبار الشخصيات.'
  },
  {
    id: "proj_warehouse_5",
    title: "بناء مستودع لوجستي في المنطقة الصناعية",
    status: "متأخر",
    variant: "destructive",
    location: "الرياض، المدينة الصناعية الثانية",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "warehouse logistics",
    progress: 80,
    budget: 12000000,
    currency: "SAR",
    lat: 24.5823,
    lng: 46.8319,
    manager: "عبدالله المصري",
    endDate: "2024-08-30",
    createdAt: "2023-09-10T08:00:00Z",
     projectType: 'industrial_warehouse',
    quality: 'standard',
    scopeOfWork: 'بناء مستودع لوجستي بمساحة 15,000 متر مربع، مع أرضيات خرسانية مصقولة، وأنظمة تخزين عالية، ومنطقة مخصصة للشحن والتفريغ.'
  },
  {
    id: "proj_hotel_6",
    title: "تشطيبات فندق 5 نجوم في الخبر",
    status: "قيد التنفيذ",
    variant: "default",
    location: "الخبر، الكورنيش",
    imageUrl: "https://placehold.co/600x400.png",
    imageHint: "hotel lobby luxury",
    progress: 75,
    budget: 45000000,
    currency: "SAR",
    lat: 26.2173,
    lng: 50.2078,
    manager: "سارة عبدالله",
    endDate: "2025-02-28",
    createdAt: "2023-07-01T12:00:00Z",
    projectType: 'hospitality_hotel',
    quality: 'luxury',
    scopeOfWork: 'أعمال التشطيبات الداخلية الفاخرة لفندق 5 نجوم، تشمل 200 غرفة وجناح، بالإضافة إلى البهو الرئيسي والمطاعم والقاعات والسبا، باستخدام مواد عالية الجودة وتصاميم مخصصة.'
  },
];
